# Generated by Django 3.1.1 on 2020-09-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAPI', '0002_auto_20200917_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='text',
        ),
    ]
